openapi: 3.0.0
info:
  title: Food API
  version: '1.0'
  description: This is my food API
  contact:
    name: Ígor Yamamoto
    email: igor@jungledevs.com
servers:
  - url: 'http://localhost:3100'
paths:
  /users:
    get:
      summary: /users
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    $ref: ../common/models/user.v1.yaml
              examples:
                example-1:
                  - id: 0
                    name: Ígor
                    age: 23
          headers: {}
      description: Return list of users
components:
  schemas: {}
  securitySchemes: {}
